include:
  - board: xiao_ble
    shield: peks48_r rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: peks48_l rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
